# Generated by Django 2.0 on 2020-03-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_server',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Server_name', models.CharField(max_length=255, unique=True)),
                ('Describe', models.TextField()),
                ('Git_url', models.CharField(max_length=255, unique=True)),
                ('Shell', models.CharField(max_length=255)),
                ('ProjectType', models.CharField(max_length=255)),
                ('Ding', models.CharField(max_length=202)),
            ],
            options={
                'verbose_name_plural': '服务名',
                'db_table': 'create_server',
                'verbose_name': '服务名',
            },
        ),
        migrations.CreateModel(
            name='exec_result_log',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Start_time', models.CharField(max_length=255)),
                ('End_time', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('Exec', models.CharField(max_length=255)),
                ('Stdout', models.TextField()),
                ('Server_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'exec_result_log',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=255)),
                ('Ticket', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
