# Generated by Django 2.0 on 2020-03-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_server',
            name='Git_url',
            field=models.CharField(max_length=255),
        ),
    ]
